package  {
	
	import flash.display.MovieClip;
	
	//Controlls bullets generated by game.
	public class Bullet extends MovieClip{

		public function Bullet(xPosition:Number, yPosition:Number) {
			this.x = xPosition;
			this.y = yPosition;
		}
		
		//Updates the position of the bullet.
		public function updatePosition() {
			this.x += 20; 
		}
		
		//Checks if bullet is still on screen.
		public function bulletGone():Boolean
		{
			return (this.x > 530);
		}

	}
	
}
