package  {
	
	import flash.display.MovieClip;
	
	//Controlls one of the enemies generated by the game.
	public class QuickEnemy extends MovieClip {
		
		private var verticalChange:int;
		private var pointsValue:int;
		private var multiplier:Number;

		public function QuickEnemy(speedMultiplier:Number) {
			this.x = 600;
			this.y = Math.floor(Math.random() * 400) + 13;
			pointsValue = 100;
			multiplier = speedMultiplier;
		}
		
		//Updates the position and points value of the enemy.
		public function UpdatePosition() {
			verticalChange = Math.floor(Math.random() * 10) - 5;
			this.x -= 5 * multiplier;
			this.y += verticalChange;
			if (pointsValue > 50) {
				pointsValue -= 1;
			}
		}
		
		//Returns the value of points for destroying the enemy.
		public function getValue():int {
			return pointsValue;
		}

	}
	
}
